//  @type {import('tailwindcss').Config}
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#ff9061",
        "surface-dim": "#0e0e0e",
        "on-surface": "#ffffff",
        "primary-fixed": "#ff793c",
        "surface-tint": "#ff9061",
        "surface-bright": "#2c2c2c",
        error: "#ff716c",
        "secondary-fixed": "#ffc789",
        "on-tertiary-fixed": "#321f00",
        "surface-container": "#1a1a1a",
        "on-primary-container": "#421300",
        "primary-container": "#ff793c",
        "inverse-surface": "#fcf9f8",
        "inverse-primary": "#a63d00",
        "on-error-container": "#ffa8a3",
        secondary: "#ffa102",
        "primary-dim": "#ff7433",
        "on-primary": "#561c00",
        "outline-variant": "#484847",
        "surface-variant": "#262626",
        "secondary-container": "#875300",
        "on-surface-variant": "#adaaaa",
        "surface-container-low": "#131313",
        tertiary: "#ffbd56",
        "on-tertiary-fixed-variant": "#5b3b00",
        "surface-container-high": "#20201f",
        surface: "#0e0e0e",
        "tertiary-container": "#f9ac20",
        "tertiary-fixed-dim": "#e99f0a",
        "on-secondary-fixed-variant": "#744600",
        "tertiary-fixed": "#f9ac20",
        "inverse-on-surface": "#565555",
        "surface-container-highest": "#262626",
        "primary-fixed-dim": "#f46823",
        "error-container": "#9f0519",
        "tertiary-dim": "#e99f0a",
        "surface-container-lowest": "#000000",
        outline: "#767575",
        "on-background": "#ffffff",
        "on-tertiary-container": "#4f3300",
        "secondary-fixed-dim": "#ffb559",
        "secondary-dim": "#ed9500",
        "on-error": "#490006",
        background: "#0e0e0e",
        "on-primary-fixed-variant": "#521a00",
        "on-tertiary": "#5b3c00",
        "on-secondary-container": "#fff6f0",
        "on-primary-fixed": "#000000",
        "error-dim": "#d7383b",
        "on-secondary": "#4d2d00",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
